[package]
edition.workspace      = true
license.workspace      = true
name                   = "herdr-client"
publish.workspace      = true
rust-version.workspace = true
version.workspace      = true

[lints]
workspace = true

[dependencies]
crossbeam-channel.workspace = true
herdr-protocol.workspace    = true
serde.workspace             = true
serde_json.workspace        = true
thiserror.workspace         = true
tracing.workspace           = true
